language: java

jdk:
  - openjdk10

before_install:
  - jdk_switcher use openjdk10
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk17
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 17 --target $JAVA_HOME
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.3-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-8.5.3-amd64.deb
  - sudo cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
  - sudo cat /etc/elasticsearch/elasticsearch.yml
  - sudo java -version
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch start
  - sleep 30

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script:
  - ulimit -a
  - mvn test
