name: Elasticsearch-Sql:branch-1

on:
  pull_request:
    branches:
      branch-1
  push:
    branches:
    - branch-1

jobs:
  build:
    strategy:
      matrix:
        jdk: [8]
        java-distribution: [zulu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.java-distribution }}
      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
