name: Elasticsearch-Sql:branch-1

on:
  pull_request:
    branches:
      branch-1
  push:
    branches:
    - branch-1

jobs:
  build:
    strategy:
      matrix:
        jdk: [17]
        java-distribution: [zulu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ matrix.java-distribution }}
      - run: |
          rm -rf /var/lib/elasticsearch
          curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb -o elasticsearch.deb && sudo dpkg -i --force-confnew elasticsearch.deb
          cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
          cat /etc/elasticsearch/elasticsearch.yml
          java -version
          chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          service elasticsearch start
          sleep 30
          mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
